
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_1.h5 --prior_idx 1 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_1.h5 --prior_idx 1 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_2.h5 --prior_idx 2 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_2.h5 --prior_idx 2 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_3.h5 --prior_idx 3 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_3.h5 --prior_idx 3 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_4.h5 --prior_idx 4 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_4.h5 --prior_idx 4 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_5.h5 --prior_idx 5 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_5.h5 --prior_idx 5 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_6.h5 --prior_idx 6 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_6.h5 --prior_idx 6 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_7.h5 --prior_idx 7 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_7.h5 --prior_idx 7 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_8.h5 --prior_idx 8 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_8.h5 --prior_idx 8 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_9.h5 --prior_idx 9 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_9.h5 --prior_idx 9 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_10.h5 --prior_idx 10 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_10.h5 --prior_idx 10 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_11.h5 --prior_idx 11 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_11.h5 --prior_idx 11 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_12.h5 --prior_idx 12 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_12.h5 --prior_idx 12 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_13.h5 --prior_idx 13 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_13.h5 --prior_idx 13 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_14.h5 --prior_idx 14 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_14.h5 --prior_idx 14 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_15.h5 --prior_idx 15 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_15.h5 --prior_idx 15 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_16.h5 --prior_idx 16 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_16.h5 --prior_idx 16 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_17.h5 --prior_idx 17 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_17.h5 --prior_idx 17 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_18.h5 --prior_idx 18 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_18.h5 --prior_idx 18 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_19.h5 --prior_idx 19 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_19.h5 --prior_idx 19 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_20.h5 --prior_idx 20 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_20.h5 --prior_idx 20 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_21.h5 --prior_idx 21 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_21.h5 --prior_idx 21 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_22.h5 --prior_idx 22 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_22.h5 --prior_idx 22 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_23.h5 --prior_idx 23 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_23.h5 --prior_idx 23 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_24.h5 --prior_idx 24 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_24.h5 --prior_idx 24 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_25.h5 --prior_idx 25 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_25.h5 --prior_idx 25 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_26.h5 --prior_idx 26 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_26.h5 --prior_idx 26 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m nb  --state_file simoutput/nb/results_27.h5 --prior_idx 27 55 --seed 42
asreview simulate data/smid_2019.csv -q max -m logistic  --state_file simoutput/logistic/results_27.h5 --prior_idx 27 55 --seed 42
